name: resplash
description: Exclusive HD Wallpaper Application


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  path_provider: ^2.0.5
  permission_handler: ^8.2.2
  intl: ^0.17.0
  dio: ^4.0.4
  image_gallery_saver: ^1.7.1
  cloud_firestore: ^2.5.3
  google_mobile_ads: ^0.13.5
  font_awesome_flutter: ^9.1.0
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_staggered_grid_view: ^0.4.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  google_sign_in: ^5.1.1
  google_fonts: ^2.1.0
  firebase_auth: ^3.1.2
  connectivity: ^3.0.6
  cached_network_image: ^3.1.0
  rate_my_app: ^1.1.1+1
  launch_review: ^3.0.1
  awesome_dialog: ^2.1.1
  shimmer: ^2.0.0
  url_launcher: ^6.0.17
  wallpaper: ^1.0.7
  firebase_core: ^1.7.0
  rounded_loading_button: ^2.0.9
  share: ^2.0.4
  onesignal_flutter: #^3.2.3
    git:
      url: https://github.com/luis901101/OneSignal-Flutter-SDK.git
      ref: migrate_android_embedding_v2



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:

    - assets/images/icon.png
    - assets/images/splash.png
    - assets/images/bridge.jpg
